Check for missing binary with init.d script part2
Change-Id: I366714a51ba54aa28ee676b34e641bfea49eef52
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

diff --git a/files/etc/init.d/nodepool-deleter b/files/etc/init.d/nodepool-deleter
--- a/files/etc/init.d/nodepool-deleter
+++ b/files/etc/init.d/nodepool-deleter
@@ -18,7 +18,10 @@ SCRIPTNAME=/etc/init.d/$NAME
 USER=nodepool
 
 # Read configuration variable file if it is present
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+if ! [ -x "$DAEMON" ]; then
+    echo "$DAEMON: command not found"
+    exit 5
+fi
 
 DAEMON=$PREFIX/bin/nodepoold
 
diff --git a/files/etc/init.d/nodepool-launcher b/files/etc/init.d/nodepool-launcher
--- a/files/etc/init.d/nodepool-launcher
+++ b/files/etc/init.d/nodepool-launcher
@@ -23,7 +23,10 @@ USER=nodepool
 DAEMON=$PREFIX/bin/nodepoold
 
 # Exit if the package is not installed
-[ -x "$DAEMON" ] || (echo "$DAEMON: command not found" && exit 5)
+if ! [ -x "$DAEMON" ]; then
+    echo "$DAEMON: command not found"
+    exit 5
+fi
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
